using System;

public class HttpEnums
{
    [Flags]
    public enum ContentType
    {
        None = 0,
        ApplicationJson = 1 << 0,
        ApplicationXml = 1 << 1,
        ApplicationXhtmlXml = 1 << 2,
        ApplicationOctetStream = 1 << 3,
        ApplicationPdf = 1 << 4,
        ApplicationRssXml = 1 << 5,
        ApplicationSoapXml = 1 << 6,
        ApplicationXwwwFormUrlencoded = 1 << 7,
        ApplicationZip = 1 << 8,
        ApplicationGzip = 1 << 9,
        ApplicationFormUrlencoded = 1 << 10,
        ApplicationAtomXml = 1 << 11,
        ApplicationRdfXml = 1 << 12,
        ApplicationFontWoff = 1 << 13,
        ApplicationFontWoff2 = 1 << 14,
        ApplicationFontTtf = 1 << 15,
        ApplicationFontEot = 1 << 16,
        ApplicationFontSvg = 1 << 17,
        ApplicationJavaScript = 1 << 18,
        ApplicationEcmascript = 1 << 19,
        TextHtml = 1 << 20,
        TextPlain = 1 << 21,
        TextCss = 1 << 22,
        TextCsv = 1 << 23,
        TextXml = 1 << 24,
        TextYaml = 1 << 25,
        TextJavascript = 1 << 26,
        ImageJpeg = 1 << 27,
        ImagePng = 1 << 28,
        ImageGif = 1 << 29,
        ImageBmp = 1 << 30,
        ImageWebp = 1 << 31,
        ImageSvgXml = 1 << 32,
        ImageIcon = 1 << 33,
        ImageTiff = 1 << 34,
        AudioMpeg = 1 << 35,
        AudioOgg = 1 << 36,
        AudioWebm = 1 << 37,
        AudioWav = 1 << 38,
        VideoMpeg = 1 << 39,
        VideoOgg = 1 << 40,
        VideoWebm = 1 << 41,
        VideoMp4 = 1 << 42,
        VideoQuicktime = 1 << 43,
        VideoAvi = 1 << 44,
        MultipartFormData = 1 << 45,
        MultipartMixed = 1 << 46,
        MultipartAlternative = 1 << 47,
        MultipartDigest = 1 << 48,
        MultipartParallel = 1 << 49,
        MultipartFormDataBoundary = 1 << 50,
        MultipartApplePicking = 1 << 51,
        MultipartXMixedReplace = 1 << 52,
        MultipartByteranges = 1 << 53,
        MultipartRelated = 1 << 54,
        MultipartReport = 1 << 55,
        MultipartSigned = 1 << 56,
        MultipartEncrypted = 1 << 57,
        Other = 1 << 58
    }
}